### ISSUE TITLE
StorybookコンポーネントをTODOアプリで利用する

### ISSUE THREAD

**Issue by tkiryc** [i3design-training/2023-yamashita.rintaro-frontend#25]
TODO
- [x] Github Repositoryを追加（2023-yamashita.rintaro-storybook)
- [x] [Storybook Tuotorialを実施](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/)
- [x] Storybookで研修TODOアプリのコンポーネントを設計
  - [x] コンポーネント設計
  - [x] コンポーネント実装
  - [x] コンポーネントをstorybookで確認
  - [x] コンポーネント繋ぎ込み
- [x] 研修TODOアプリでStorybookコンポーネントを再利用する
- [x] ブラッシュアップしたTODOアプリをデモンストレーション

**Comment by YamashitaRintaro** [comment]
https://www.notion.so/i3design/1116fa32bf044471bea9a1adf71fb089?v=342ce71220134599941bc551c157c17b&pvs=4
