### ISSUE TITLE
フロントエンド：React Library

### ISSUE THREAD

**Issue by tkiryc** [i3design-training/2023-yamashita.rintaro-frontend#27]
TODO
- [x] [Redux](https://redux.js.org/introduction/getting-started)のドキュメントを読む
- [x] Reduxを研修TODOアプリへ組み込む
- [x] [RTK Query（Redux Toolkit）](https://redux-toolkit.js.org/rtk-query/overview)のドキュメントを読む
- [x] RTK Queryを研修TODOアプリへ組み込む
- [x] formを[React Hook Form](https://www.react-hook-form.com/)に修正

**Comment by YamashitaRintaro** [comment]
7/21 予定

- [x] 午前中にReduxのIntroductionを読み、概要を[Notion](https://www.notion.so/i3design/1116fa32bf044471bea9a1adf71fb089?v=342ce71220134599941bc551c157c17b&p=57767e396a0748e79acca4d94e30ccea&pm=s)にまとめる
  - [x] 理解するまではいかなくとも、概要を理解する。
- [x] 午後にReduxのTutorialsをハンズオンで行う。土日に復習してNotionにまとめる
  - [x] 理解するまではいかなくとも、概念を理解する。引き出しとして頭の隅に置いておく。

**Comment by YamashitaRintaro** [comment]
何を持って完了とするかを決める。

**Comment by YamashitaRintaro** [comment]
7/24 予定

- [x] 午前中にReduxのTutorialsを終わらせる
- [x] 7月前半に作成したtodoアプリにreduxを組み込む
  - [x] ログイン機能をredux化

**Comment by YamashitaRintaro** [comment]
悩んでいること
- ディレクトリ構成どうするべき？
- SPAでどうReduxを組み込むべき？
- どこまでredux化するべき？

**Comment by YamashitaRintaro** [comment]
7/25 予定

- [x] 引き続き7月前半に作成したtodoアプリにreduxを組み込む
  - [x] ユーザーのcrudをredux化
  - [x] taskのcrudをredux化

**Comment by YamashitaRintaro** [comment]
メモ化すればいいというもんじゃない。毎回計算するコストと、メモ化するコストを比べる。

**Comment by YamashitaRintaro** [comment]
7/26 予定
 - [x] taskの一覧取得をメモ化でパフォーマンスUP
 - [x] [RTK Query（Redux Toolkit）](https://redux-toolkit.js.org/rtk-query/overview)のドキュメントを読む

**Comment by YamashitaRintaro** [comment]
7/27 予定

- [x] [RTK Query Basics](https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics)の内容をTODOアプリに組み込む
- [x] [RTK Query（Redux Toolkit）](https://redux-toolkit.js.org/rtk-query/overview)のドキュメントを読む
  - [x] なぜこの技術を使うのか、他の技術よりも優れている点はどこかを理解して[Notion](https://www.notion.so/i3design/RTK-Query-2dc26c00752b4c15965d06f0a997d5ba?pvs=4)にまとめる。

**Comment by YamashitaRintaro** [comment]
7/28 予定
- [x] [React Hook Form](https://www.react-hook-form.com/)を読み込む
- [x] formを[React Hook Form](https://www.react-hook-form.com/)に修正
